[project]
name = "gaussian-splatting-with-rerun"
version = "0.1.0"
description = "Code Gaussian Splatting from Scratch and visualize with Rerun"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "rerun-sdk>=0.27.3",
    "torch>=2.9.1",
]
